name: Release

on:
push:
branches:
- main

permissions:
contents: write

jobs:
reapack:
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v4

  - name: Install reapack-index
    run: gem install reapack-index

  - name: Build ReaPack index
    run: reapack-index --commit --amend
```
