name: Release
on:
  push:
    branches:
      - main
jobs:
  reapack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cfillion/reapack-actions@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
